title: The Scala Programming Language

scalaversion: "2.11.7"
devscalaversion: "2.12.0-M3"

baseurl: ""
exclude: ["vendor"]

markdown: redcarpet
highlighter: null
redcarpet:
  extensions: ["no_intra_emphasis", "fenced_code_blocks", "autolink", "tables", "with_toc_data", "strikethrough", "lax_spacing", "space_after_headers", "superscript", "footnotes"]
